<TABLE BORDER="0" WIDTH="100%" ALIGN="CENTER" CELLPADDING="0" CELLSPACING="0">
<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="5"><FONT FACE="Verdana" SIZE="2"><b>Business Name</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Status</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>No Tables<BR>Where Used</B></FONT>
</TD>
</TR>

<TR>
<TD COLSPAN="5"><FONT FACE="Verdana" SIZE="2"><%=strElemBName%></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strRelObjStatus%></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=iTblCount %></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strHeaderColor%>">
<!--
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Create Date</B></FONT>
</TD>
-->
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Created By</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Last Modified</B></FONT>
</TD>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><b>Last Modified By</B></FONT>
</TD>
</TR>

<TR>
<!--
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strElemCreateTS%></FONT>
</TD>
-->
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strElemCreateUID%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strElemLstChngTS%></FONT>
</TD>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><%=strElemLstChngUID%></FONT>
</TD>
</TR>
</TABLE>
<TABLE BORDER="0" WIDTH="100%" ALIGN="CENTER" CELLPADDING="0" CELLSPACING="0">
<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="4"><FONT FACE="Verdana" SIZE="2"><b>Column Name</B></FONT>
</TD>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><b>Dictionary Name</B></FONT>
</TD>
</TR>
<TR>
<TD COLSPAN="4"><FONT FACE="Verdana" SIZE="2"><%=strElemCName%></FONT>
</TD>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><%=strElemDName%></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><b>Data Type</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Length</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Decimal Length</B></FONT>
</TD>
</TR>

<TR>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><%=strElemDataType%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strElemPlen%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strElemDlen%></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="7"><FONT FACE="Verdana" SIZE="2"><b>Description</B></FONT>
</TD>
</TR>
<TR>
<TD COLSPAN="7"><FONT FACE="Verdana" SIZE="2"><%=strElemDesc%></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="6"><FONT FACE="Verdana" SIZE="2"><b>Tables Where Used</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Status</B></FONT>
</TD>
</TR>
