<%
'COLORS.INC
Dim aryPageColors(24)  'Set the page colors
Dim strHeaderColor
Dim strBackColor
Dim strTextColor
Dim strPageBackColor
Dim strLinkColor
Dim strALinkColor
Dim strVLinkColor
Dim strMenuSelColor
Dim strProdColor
Dim strDvlpColor
Dim strItstColor
Dim strApprColor

aryPageColors(0)  = "#000000"     'Black
aryPageColors(1)  = "#FFFFFF"     'White
aryPageColors(2)  = "#003399"     'Blue
aryPageColors(3)  = "#996633"     'Brown
aryPageColors(4)  = "#FFCC66"     'Yellow
aryPageColors(5)  = "#FF9933"     'Orange
aryPageColors(6)  = "#708090"     'Grey
aryPageColors(7)  = "#CCCC99"     'drk Grey-Green
aryPageColors(8)  = "#CC6600"     'Dark orange
aryPageColors(9)  = "#EEEECC"     'light grey hint green
aryPageColors(10) = "#FFCC00"    'Orange Yellow
aryPageColors(11) = "#003366"    'Michgan blue
aryPageColors(12) = "#FF0000"    'Red
aryPageColors(13) = "#FF00FF"  'lght blue
aryPageColors(14) = "#008FFF"  'magenta
aryPageColors(15) = "#FF00FF"  'lght blue
aryPageColors(16) = "#9933FF"  'chocolate
aryPageColors(17) = "#FF00FF"  'lght blue
aryPageColors(18) = "#3366FF"  'Dark blue
aryPageColors(19) = "#CCFFCC"  'lght blue
aryPageColors(20) = "#A4A6FF"  'Nav Blue
aryPageColors(21) = "#3366CC"  'Chill Blue
aryPageColors(22) = "#0000FF"  'Real blue
aryPageColors(23) = "#00003C"  'Darker Tan
aryPageColors(24) = "#3366FF"  'Sky Blue

strHeaderColor=aryPageColors(7)
strPageBackColor=aryPageColors(1)
strBackColor=aryPageColors(9)
strTextColor=aryPageColors(0)
strLinkColor=aryPageColors(2)
strALinkColor=aryPageColors(2)
strVLinkColor=aryPageColors(2)
strMenuSelColor=aryPageColors(22)
strMenuHeaderColor=aryPageColors(11)
strMenuBackColor=aryPageColors(18)
strMenuTextColor=aryPageColors(1)
strErrTextColor=aryPageColors(12)
strTextHLTColor=aryPageColors(22)
strProdColor = aryPageColors(0)
strDvlpColor = aryPageColors(13)
strAprvColor = aryPageColors(14)
strItstColor = aryPageColors(16)
strLineColor = aryPageColors(7)
%>
