vti_encoding:SR|utf8-nl
vti_author:SR|izzy
vti_cachedlinkinfo:VX|S|../images/report_trans.gif H|elmdtl.asp S|../images/report80_trans.gif S|../images/line2.gif
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_timecreated:TR|28 Feb 2002 01:54:30 -0500
vti_filesize:IX|5226
vti_cachedbodystyle:SR|<body>
vti_modifiedby:SR|izzy
vti_cacheddtm:TX|28 Feb 2002 01:54:30 -0500
vti_backlinkinfo:VX|
vti_cachedhasbots:BR|false
vti_extenderversion:SR|3.0.2.926
vti_timelastmodified:TR|28 Feb 2002 01:54:30 -0500
