<TABLE BORDER="0" WIDTH="100%" ALIGN="CENTER" CELLPADDING="0" CELLSPACING="0">

<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="4"><FONT FACE="Verdana" SIZE="2"><b>Server Name</B></FONT>
</TD>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><b>No of Databases</B></FONT>
</TD>
</TR>

<TR>
<TD COLSPAN="4"><FONT FACE="Verdana" SIZE="2"><%=strRelObjName%></FONT>
</TD>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><%=iDbCount %></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strHeaderColor%>">
<TD><FONT FACE="Verdana" SIZE="2"><b>OS Name</B></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><b>OS Version</B></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><b>Location Code</B></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><b>Create Date</B></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><b>Created By</B></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><b>Last Modified</B></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><b>Last Modified By</B></FONT>
</TD>
</TR>

<TR>
<TD><FONT FACE="Verdana" SIZE="2"><%=strOSName%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strOSVer%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strLocation%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strCreateTS%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strCreateUID%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strLastChngTS%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strLastChngUID%></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="7"><FONT FACE="Verdana" SIZE="2"><B>Description</B></FONT>
</TD>
<TR>
<TD COLSPAN="7"><FONT FACE="Verdana" SIZE="2"><%=strDesc%></FONT>
</TD>
</TABLE>

<TABLE BORDER="0" WIDTH="100%" ALIGN="CENTER" CELLPADDING="0" CELLSPACING="0">
<TR BGCOLOR="<%=strHeaderColor%>">
<TD><FONT FACE="Verdana" SIZE="2"><b>Database Name</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Database Description</B></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><b>Status</B></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><b>No of Tables</B></FONT>
</TD>
</TR>
