<TABLE BORDER="0" WIDTH="100%" ALIGN="CENTER" CELLPADDING="0" CELLSPACING="0">

<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Table Name</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>In Database</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Status</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>No of Elements</B></FONT>
</TD>
</TR>

<TR>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strRelObjName%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strDatabase%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strRelObjStatus%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=iElemCount %></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Owner</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Create Date</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Created By</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Last Modified</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Last Modified By</B></FONT>
</TD>
</TR>

<TR>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strTblOwner%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strCreateTS%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strCreateUID%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strLastChngTS%></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strLastChngUID%></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><B>Description</B></FONT>
</TD>
<TR>
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><%=strDesc%></FONT>
</TD>
</TR>
</TABLE>

<TABLE BORDER="0" WIDTH="100%" ALIGN="CENTER" CELLPADDING="0" CELLSPACING="0">
<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><b>Element Business Name</B></FONT>
</TD>
</TR>
<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Data<br>Type</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Length</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Decimal<br>Length</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Null Code</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Status</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Version</B></FONT>
</TD>
</TR>
