<TR BGCOLOR="<%=strBackColor%>">
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><b><%=strElemBName%></B></FONT>
</TD>
</TR>
<TR>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strElemDataType%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strElemPlen%></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strElemDlen%></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strElemNullCode%></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strElemStatus%></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strElemVer%></FONT>
</TD>
</TR>
<TR>
<TD COLSPAN="8" HEIGHT="20" ALIGN="center">
</TD>
</TR>