<TR BGCOLOR="<%=strBackColor%>">
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><b>Table Name</B></FONT>
</TD>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><b>Status</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>No of Elements</B></FONT>
</TD>
</TR>

<TR>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><%=strTableName%></FONT>
</TD>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><%=strTableStatus%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=iElemCount %></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strBackColor%>">
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Owner</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Create Date</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Created By</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Last Modified</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Last Modified By</B></FONT>
</TD>
</TR>

<TR>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strTableOwner%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strTableCreateTS%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strTableCreateUID%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strTableLstChngTS%></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strTableLstChngUID%></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strBackColor%>">
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><B>Description</B></FONT>
</TD>
<TR>
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><%=strTableDesc%></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strBackColor%>">
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><b>Elements</B></FONT>
</TD>
</TR>
