<TR BGCOLOR="<%=strBackColor%>">
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><b>Business Name</B></FONT>
</TD>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><b>Dictionary Name</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Column Name</B></FONT>
</TD>
</TR>
<TR>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><%=strElemBName%></FONT>
</TD>
<TD COLSPAN="3"><FONT FACE="Verdana" SIZE="2"><%=strElemDName%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strElemCName%></FONT>
</TD>
</TR>
<TR BGCOLOR="<%=strBackColor%>">
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Primary Key</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Data Type</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Length</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Length</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Null Code</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Default</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Status</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Version</B></FONT>
</TD>
</TR>
<TR>
<TD><FONT FACE="Verdana" SIZE="2"><%=strElemPrimKey%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strElemDataType%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strElemPLen%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strElemDLen%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strElemNullCode%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strElemDefault%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strElemStatus%></FONT>
</TD>
<TD><FONT FACE="Verdana" SIZE="2"><%=strElemVer%></FONT>
</TD>
</TR>
<TR BGCOLOR="<%=strBackColor%>">
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><b>Description</B></FONT>
</TD>
</TR>
<TR>
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><%=strElemDesc%></FONT>
</TD>
</TR>
<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="8" HEIGHT="20" ALIGN="center">
</TD>
</TR>