<TABLE BORDER="0" WIDTH="100%" ALIGN="CENTER" CELLPADDING="0" CELLSPACING="0">
<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Business Name</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Status</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>In Server</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>No of Tables</B></FONT>
</TD>
</TR>

<TR>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strDbBName%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strRelObjStatus%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strServer%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=iTableCount %></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>RDBMS Name</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>RDBMS Version</B></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Create Date</B></FONT>
</TD>
<!--
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Created By</B></FONT>
</TD>
-->
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><b>Last Modified</B></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><b>Last Modified By</B></FONT>
</TD>
</TR>

<TR>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strRDBMS%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strRDBMSVer%></FONT>
</TD>
<!--
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strCreateTS%></FONT>
</TD>
-->
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strCreateUID%></FONT>
</TD>
<TD COLSPAN="1"><FONT FACE="Verdana" SIZE="2"><%=strLastChngTS%></FONT>
</TD>
<TD COLSPAN="2"><FONT FACE="Verdana" SIZE="2"><%=strLastChngUID%></FONT>
</TD>
</TR>

<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><B>Description</B></FONT>
</TD>
<TR>
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><%=strDesc%></FONT>
</TD>
</TABLE>

<TABLE BORDER="0" WIDTH="100%" ALIGN="CENTER" CELLPADDING="0" CELLSPACING="0">
<TR BGCOLOR="<%=strHeaderColor%>">
<TD COLSPAN="8"><FONT FACE="Verdana" SIZE="2"><b>Tables</B></FONT>
</TD>
</TR>
